### ISSUE TITLE
Remove auto-generated API from VCS

### ISSUE THREAD

**Issue by 0x009922** [fraud-intelligence-limited/fil-documentation#13]
It seems that pages in `API_Specification` are generated by some tool. In order to avoid keeping auto-generated files in VCS, consider legeraging [Build-Time Data Loading | VitePress](https://vitepress.dev/guide/data-loading) feature. Both sidebar and pages content could be generated with simple scripts.

**Comment by yamkovoy** [comment]
We discussed this issue with @0x009922 and came to the conclusion that it is not relevant anymore.
