### ISSUE TITLE
Expand tutorials with signing email [JavaScript]

### ISSUE THREAD

**Issue by Mingela** [fraud-intelligence-limited/fil-documentation#38]
https://github.com/fraud-intelligence-limited/fil-documentation/issues/34

**Comment by 0x009922** [comment]
@Mingela, I miss some details to build an example. In particular, I am confused by the form of the private key.

In the Java example, it is just a hex string. However, in Iroha private key is never represented as a simple hex - it is always a pair `digest_function` + `payload` (hex).

Is the digest function of the private key is always known? In the [Generating key pairs | FIB Documentation](https://fraud-intelligence-limited.github.io/tutorials-api/generating-key-pairs.html) guide I see only the mentions of Blake2b-256 hash, which is not suitable here.

**Comment by Mingela** [comment]
Referring to the comment above, currently only `ed` is used so should be treated as default one. So yes, it's always known. As for the Generating key pairs chapter, that hash is used for a seed generating (rather as a recommended algorithm) and does not really have much in common with the subject.
