### ISSUE TITLE
Use `http` syntax for desribing HTTP requests

### ISSUE THREAD

**Issue by 0x009922** [fraud-intelligence-limited/fil-documentation#4]
### Description

There are multiple places with the following formula:
 
> Send a `POST` request to the `/data/api/v1/contribution-management/contribution/assemble` endpoint with the following data specified in the body of the request:

Code block with `http` syntax could be used instead:

````md
**Method & URL:**

```http
POST /data/api/v1/contribution-management/contribution/assemble
```

**Request body:**
````

> **Method & URL:**
> 
> ```http
> POST /data/api/v1/contribution-management/contribution/assemble
> ```
> 
> **Request body:**

It will not only help to avoid putting `<br>` so the long path will not be wrapped, but also will allow readers to easily copy the url (with method, though).

**Comment by yamkovoy** [comment]
Resolved in pull request #32
