### ISSUE TITLE
Fix logos

### ISSUE THREAD

**Issue by 0x009922** [fraud-intelligence-limited/fil-documentation#46]
Comes from #45:

- [ ] Logos should be provided in a single scale, and preferable as SVGs
- [ ] Logos should support dark theme. Currently I have to set their background to white, which looks awful. Simple grayscale version for dark theme is fine, I think

**Comment by Mingela** [comment]
Please also consider making those clickable redirecting to the respective websites (https://www.orillionsolutions.com/, https://soramitsu.co.jp/)
