### ISSUE TITLE
Too many spoilers

### ISSUE THREAD

**Issue by 0x009922** [fraud-intelligence-limited/fil-documentation#5]
### Description

There are plenty of places like this:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/43530070/231070607-fb9342e4-d7c1-446a-a80c-81c81431eea8.png">

I struggled with it. I had to click 4 times just to see what is there, click 4 times more to close it, and all of this accompanied with layout shifts. Not the best user experience.

In most cases, hidden snippets are very small, and there is no problem if it is just rendered. In fact, most of them are also not "optional" data - I needed to see them all in order to understand what is meant by "input structure" or by "output example". 

Spoilers are good, but when the data they hide is unlikely to be opened in most cases, or when it is huge.

If spoilers are really needed (which I am quite sceptical about), at least combine 4 sequential spoilers into a single one.

**Comment by yamkovoy** [comment]
Resolved in pull request #32
